--Drop tables only if needed
/*  DROP TABLE T1;
    DROP TABLE T2;
    DROP TABLE T3;
*/

--Create tables
CREATE COLUMN TABLE T1 (A INTEGER, B INTEGER);
CREATE COLUMN TABLE T2 (C INTEGER, D INTEGER, E INTEGER, PRIMARY KEY (C, D));
CREATE COLUMN TABLE T3 (F INTEGER, G INTEGER, H INTEGER, PRIMARY KEY (F, G));


--Insert values
INSERT INTO T1 SELECT GENERATED_PERIOD_START AS A, TO_INT(RAND()*100) AS B FROM SERIES_GENERATE_INTEGER(1, 1, 100001);
INSERT INTO T2 SELECT GENERATED_PERIOD_START AS C, TO_INT(RAND()*10) AS D, TO_INT(RAND()*1000) AS E FROM SERIES_GENERATE_INTEGER(1, 1, 10000001); 
INSERT INTO T3 SELECT GENERATED_PERIOD_START AS F, TO_INT(RAND()*10) AS G, TO_INT(RAND()*1000) AS H FROM SERIES_GENERATE_INTEGER(1, 1, 10000001); 
COMMIT;

-- Merging
MERGE DELTA OF T1;
MERGE DELTA OF T2;
MERGE DELTA OF T3;


--Run problematic query
SELECT 
  T1.A, 
  T1.B, 
  T4.C, 
  T4.E, 
  T4.H
FROM T1
LEFT OUTER JOIN (
  SELECT 
    T2.C,
    SUM(CASE WHEN T2.E>10 THEN 10 ELSE 0 END) AS E,
    SUM(CASE WHEN T3.H<=50 THEN 0 ELSE T3.H END) AS H 
  FROM T2 
  JOIN T3 
  ON ( T2.C=T3.F AND T2.D=T3.G)
  GROUP BY T2.C ) T4
ON (T1.A=T4.C)
ORDER BY T1.A
LIMIT 20 WITH HINT (IGNORE_PLAN_CACHE);
