
SELECT 
  T1.A, 
  T1.B, 
  T4.C, 
  T4.E, 
  T4.H 
FROM T1
LEFT OUTER JOIN (
  SELECT 
    T2.C,
    SUM(CASE WHEN T2.E>10 THEN 10 ELSE 0 END) AS E, 
    SUM(CASE WHEN T3.H<=50 THEN 0 ELSE T3.H END) AS H
  FROM T2 
  JOIN T3 
    ON (T2.C=T3.F AND T2.D=T3.G) 
  INNER JOIN T1 
    ON (T2.C = T1.A)
  GROUP BY T2.C ) T4 
ON (T1.A=T4.C)
ORDER BY T1.A
LIMIT 20 WITH HINT (IGNORE_PLAN_CACHE);
